package onpu.diplom.mironov.cew.view;

import javax.swing.Icon;
import onpu.diplom.mironov.cew.CewUtil;
import onpu.diplom.mironov.cew.bean.DeviceType;
import onpu.diplom.mironov.cew.bean.Room;
import onpu.diplom.mironov.cew.model.CewCellRenderer;

public class NewDevicePanel extends javax.swing.JPanel {
    private DeviceType[] deviceTypes;
    private Room[] rooms;

    /**
     * Creates new form NewDevicePanel
     * @param deviceTypes
     * @param rooms
     */
    public NewDevicePanel(DeviceType[] deviceTypes, Room[] rooms) {
        this.deviceTypes = deviceTypes;
        this.rooms = rooms;
        initComponents();
        deviceComboBox.setRenderer(new CewCellRenderer<DeviceType>(){
            @Override
            protected String getText(DeviceType value) {
                return value.getTitle();
            }
            @Override
            protected Icon getIcon(DeviceType value) {
                return CewUtil.createScaledImageIcon(value.getImageUrl());
            }
        });
        roomComboBox.setRenderer(new CewCellRenderer<Room>(){
            @Override
            protected String getText(Room value) {
                return value.getNumber() + " \"" + value.getTitle() + "\"";
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        deviceComboBox = new javax.swing.JComboBox<DeviceType>();
        jLabel2 = new javax.swing.JLabel();
        roomComboBox = new javax.swing.JComboBox<Room>();
        jLabel3 = new javax.swing.JLabel();
        hashTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextPane = new javax.swing.JTextPane();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("i18n/ru"); // NOI18N
        jLabel1.setText(bundle.getString("panel.newdevice.deviceTypeId.label")); // NOI18N

        deviceComboBox.setModel(new javax.swing.DefaultComboBoxModel<DeviceType>(this.deviceTypes));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText(bundle.getString("panel.newdevice.roomId.label")); // NOI18N

        roomComboBox.setModel(new javax.swing.DefaultComboBoxModel<Room>(this.rooms));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText(bundle.getString("panel.newdevice.hash.label")); // NOI18N

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText(bundle.getString("panel.newdevice.description.label")); // NOI18N

        jScrollPane1.setViewportView(descriptionTextPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deviceComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roomComboBox, 0, 202, Short.MAX_VALUE)
                    .addComponent(hashTextField)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(deviceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(roomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(hashTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane descriptionTextPane;
    private javax.swing.JComboBox<DeviceType> deviceComboBox;
    private javax.swing.JTextField hashTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Room> roomComboBox;
    // End of variables declaration//GEN-END:variables

    public DeviceType getSelectedDeviceType() {
        return (DeviceType) deviceComboBox.getSelectedItem();
    }

    public Room getSelectedRoom() {
        return (Room) roomComboBox.getSelectedItem();
    }

    public String getHashText() {
        return hashTextField.getText().trim();
    }

    public String getDescriptionText() {
        return descriptionTextPane.getText().trim();
    }
}
